/**
 * Seed data barrel — GENERATED by scripts/build-seed.mjs (do not edit by hand; run `npm run build:seed`).
 *
 * Static JSON imports so Vercel bundles every file (no fs / glob at runtime).
 * Format: `SeedMeetingFile` / `SeedWorkspaceFile` in `@/lib/types`.
 */
import type { SeedMeetingFile, SeedWorkspaceFile } from "@/lib/types";

import workspace from "./workspace.json";
import q4RoadmapPlanning from "./meetings/q4-roadmap-planning.json";
import designReview from "./meetings/design-review.json";
import priyaMarcus1on1 from "./meetings/priya-marcus-1on1.json";
import weeklyStandup from "./meetings/weekly-standup.json";
import acmeDiscovery from "./meetings/acme-discovery.json";
import pricingPagePlanning from "./meetings/pricing-page-planning.json";
import staffEngineerInterview from "./meetings/staff-engineer-interview.json";
import globexQbr from "./meetings/globex-qbr.json";
import vendorSecurityReview from "./meetings/vendor-security-review.json";

export const seedWorkspace = workspace as unknown as SeedWorkspaceFile;

/** Newest first. */
export const seedMeetings = [
  q4RoadmapPlanning,
  designReview,
  priyaMarcus1on1,
  weeklyStandup,
  acmeDiscovery,
  pricingPagePlanning,
  staffEngineerInterview,
  globexQbr,
  vendorSecurityReview,
] as unknown as SeedMeetingFile[];
