/**
 * Seed file formats owned by the database agent (Phase 5). Generated by scripts/build-seed.mjs from
 * seed-src/parity.json into src/data/seed/parity.json; loaded by SeedRepo and scripts/seed.mts.
 * Type-only module (no runtime imports) so Node can load it from scripts via type stripping.
 */
import type {
  CalendarEvent,
  Comment,
  CrmSyncLog,
  DealOverrides,
  Folder,
  Notification,
  Reaction,
  SlackConfig,
  TeamMember,
  Tracker,
  UserPrefs,
  Webhook,
  WebhookDelivery,
} from "../types";

/** Calendar event as stored (the effective `record` flag is computed at read time from the auto-record rule). */
export type StoredCalendarEvent = Omit<CalendarEvent, "record">;

export interface SeedParityFile {
  folders: Folder[];
  /** meeting id → emails the meeting is explicitly shared with ("Shared with me" tab). */
  meeting_invites: Record<string, string[]>;
  team_members: TeamMember[];
  comments: Comment[];
  reactions: Reaction[];
  trackers: Tracker[];
  deal_overrides: (DealOverrides & { name?: string })[];
  notifications: Notification[];
  webhooks: Webhook[];
  webhook_deliveries: WebhookDelivery[];
  slack_config: SlackConfig;
  crm_sync_logs: CrmSyncLog[];
  prefs: UserPrefs;
}
